from base import BaseUNGTest
import unittest

import re

class TestUNGGadgetInUNGDocs(BaseUNGTest):
    def test_ung_gadget_in_ung_docs(self):
        sel = self.selenium
        self.init()
        self.login_as_default_user()
        self.failUnless(sel.is_text_present("Please use link (Add gadgets) to prepare it yourself."))
        self.assertEqual("Add gadgets", sel.get_text("//a[@id=\"add-gadgets\"]/span"))
        self.failIf(sel.is_text_present("Join ERP5 Network !"))
        self.failIf(sel.is_element_present("//a[@class=\"clickable-block block-remove\"]"))
        sel.click("//a[@id=\"add-gadgets\"]")
        self.failUnless(sel.is_text_present("Add Gadget"))
        sel.click("//input[@id=\"erp5_documentation\"]")
        sel.click("//div[@class=\"ui-dialog-buttonset\"]/button[1]")
        sel.wait_for_page_to_load("30000")
        self.failUnless(sel.is_text_present("Join ERP5 Network !"))
        self.failUnless(sel.is_element_present("//a[@class=\"clickable-block block-remove\"]"))
        self.failIf(sel.is_element_present("//div[@id=\"page_wrapper\"]/div[1]/h4"))
        sel.click("//a[@class=\"clickable-block block-remove\"]")
        self.failUnless(re.search(r"^Are you sure you want to remove this gadget from your personalized page[\s\S]$", sel.get_confirmation()))
        self.wait_for_activities()
        sel.open("")
        sel.wait_for_page_to_load("30000")
        self.assertEqual("Add gadgets", sel.get_text("//a[@id=\"add-gadgets\"]/span"))
        sel.click("//a[@id=\"add-gadgets\"]")
        sel.click("//input[@id=\"erp5_rss\"]")
        sel.click("//div[@class=\"ui-dialog-buttonset\"]/button[1]")
        sel.wait_for_page_to_load("30000")
        self.assertEqual("Feed Reader", sel.get_text("//span[@class=\"gadget_title\"]"))
        sel.click("//a[@class=\"clickable-block block-remove\"]")
        self.failUnless(re.search(r"^Are you sure you want to remove this gadget from your personalized page[\s\S]$", sel.get_confirmation()))
        self.wait_for_activities()
        sel.open("")
        sel.wait_for_page_to_load("30000")
        self.failIf(sel.is_element_present("//a[@class=\"clickable-block block-remove\"]"))
        #  Test add two gadgets
        sel.click("//a[@id=\"add-gadgets\"]")
        sel.click("//input[@id=\"erp5_documentation\"]")
        sel.click("//input[@id=\"erp5_rss\"]")
        sel.click("//div[@class=\"ui-dialog-buttonset\"]/button[1]")
        sel.wait_for_page_to_load("30000")
        self.assertEqual("Feed Reader", sel.get_text("//span[@class=\"gadget_title\"]"))
        self.failUnless(sel.is_text_present("Join ERP5 Network !"))
        sel.click("//div[@id=\"portal-column-0\"]/div[1]/h3/span/a[@title=\"Remove\"]")
        self.failUnless(re.search(r"^Are you sure you want to remove this gadget from your personalized page[\s\S]$", sel.get_confirmation()))
        self.wait_for_activities()
        sel.open("")
        sel.wait_for_page_to_load("30000")
        self.failIf(sel.is_element_present("//div[@id=\"portal-column-0\"]/div[2]/h3/span/a[@title=\"Remove\"]"))
        self.failUnless(sel.is_text_present("Join ERP5 Network !"))
        sel.click("//a[@class=\"clickable-block block-remove\"]")
        self.failUnless(re.search(r"^Are you sure you want to remove this gadget from your personalized page[\s\S]$", sel.get_confirmation()))
        self.wait_for_activities()
        sel.open("?reset:int=1")
        sel.wait_for_page_to_load("30000")
        self.failIf(sel.is_element_present("//a[@class=\"clickable-block block-remove\"]"))
        #  Test gadget with different users
        sel.click("//a[@id=\"add-gadgets\"]")
        sel.click("//input[@id=\"erp5_documentation\"]")
        sel.click("//input[@id=\"erp5_rss\"]")
        sel.click("//div[@class=\"ui-dialog-buttonset\"]/button[1]")
        sel.wait_for_page_to_load("30000")
        self.wait_for_activities()
        sel.open("WebSite_logout")
        sel.wait_for_page_to_load("30000")
        #XXX user already created
#        sel.click("//td[@id=\"new-account-form\"]")
#        sel.type("//input[@name=\"firstname\"]", "Another")
#        sel.type("//input[@name=\"lastname\"]", "User")
#        sel.type("//input[@name=\"email\"]", "example2@example.com")
#        sel.type("//input[@name=\"login_name\"]", "ung_user2")
#        sel.type("//input[@name=\"password\"]", "1234")
#        sel.type("//input[@name=\"confirm\"]", "1234")
#        sel.click("//input[@value=\"Create Account\"]")
#        sel.wait_for_page_to_load("30000")
        sel.type("__ac_name", "ung_user2")
        sel.type("__ac_password", "1234")
        sel.click("//input[@type=\"submit\"]")
        sel.wait_for_page_to_load("30000")
        self.failUnless(sel.is_text_present("Please use link (Add gadgets) to prepare it yourself."))
        self.failIf(sel.is_text_present("Join ERP5 Network !"))
        sel.click("//a[@id=\"add-gadgets\"]")
        sel.click("//input[@id=\"erp5_worklists\"]")
        sel.click("//div[@class=\"ui-dialog-buttonset\"]/button[1]")
        sel.wait_for_page_to_load("30000")
        self.assertEqual("ERP5 Worklists", sel.get_text("//span[@class=\"gadget_title\"]"))
        sel.open("WebSite_logout")
        sel.wait_for_page_to_load("30000")
        self.login_as_default_user()
        self.assertNotEqual("ERP5 Worklists", sel.get_text("//span[@class=\"gadget_title\"]"))
        self.assertEqual("Feed Reader", sel.get_text("//span[@class=\"gadget_title\"]"))
        self.failUnless(sel.is_text_present("Join ERP5 Network !"))
        sel.open("WebSite_logout")
        sel.wait_for_page_to_load("30000")
        sel.type("__ac_name", "zope")
        sel.type("__ac_password", "zope")
        sel.click("//input[@type=\"submit\"]")
        sel.wait_for_page_to_load("30000")
        self.failUnless(sel.is_text_present("Please use link (Add gadgets) to prepare it yourself."))
        sel.click("//a[@id=\"add-gadgets\"]")
        sel.click("//input[@id=\"erp5_worklists\"]")
        sel.click("//div[@class=\"ui-dialog-buttonset\"]/button[1]")
        sel.wait_for_page_to_load("30000")
        self.assertEqual("ERP5 Worklists", sel.get_text("//span[@class=\"gadget_title\"]"))
        sel.click("//a[@class=\"clickable-block block-remove\"]")
        self.failUnless(re.search(r"^Are you sure you want to remove this gadget from your personalized page[\s\S]$", sel.get_confirmation()))
        self.wait_for_activities()
        sel.open("WebSite_logout")
        sel.wait_for_page_to_load("30000")
        self.login_as_default_user()
        self.assertNotEqual("ERP5 Worklists", sel.get_text("//span[@class=\"gadget_title\"]"))
        self.assertEqual("Feed Reader", sel.get_text("//span[@class=\"gadget_title\"]"))
        self.failUnless(sel.is_text_present("Join ERP5 Network !"))

        #XXX clean gadgets from all users after test
        # maybe using KnowledgePad tool
        # url: http://localhost:18080/erp5/portal_skins/erp5_web_ung_theme/WebSection_viewMenuWidget/pt_editForm
        # starting at <div class="front_pad">

if __name__ == "__main__":
    unittest.main()

